### ISSUE TITLE
Unity 2021.3.21f1 wants to access mUnityPlayer field

### ISSUE THREAD

**Issue by Luluno01** [azesmway/react-native-unity#68]
After upgrading to editor version 2021.3.21f1, Android build is no longer working:

```
E Unity   : AndroidJavaException: java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "mUnityPlayer" in class "Lcom/example/MainActivity;" or its superclasses
E Unity   : java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "mUnityPlayer" in class "Lcom/example/MainActivity;" or its superclasses
E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E Unity   :      at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)
E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)
E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
E Unity   :      at android.os.Looper.loop(Looper.java:233)
E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
E Unity   :   at UnityEngine.AndroidJNISafe.GetFieldID (System.IntPtr clazz, System.String name, System.String sig) [0x00000] in <00000000000000000000000000000000>:0
E Unity   :   at UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.Str
```

Somehow the Unity native code wants to access `mUnityPlayer` field of current activity class, which is never defined but it worked in previous versions. After looking into the built-in `UnityPlayerActivity` I found `protected UnityPlayer mUnityPlayer; // don't change the name of this variable; referenced from native code`, which has been there before it breaks. So it looks like there is change in the native code, but I can't find the source code of it.

**Comment by Luluno01** [comment]
Found a similar report https://stackoverflow.com/questions/75728722/flutter-unity-integration-errorandroidjavaexception-java-lang-nosuchfielderror

It seems Unity has changed the way it interacts with the hosting activity. Just don't know why the native code will need the `mUnityPlayer` field and what the native code is expecting from the hosting activity.

**Comment by stockhuman** [comment]
We haven't run into your particular issue, but we're also seeing a myriad of compilation errors to do with the `UnityPlayer` class & its view methods, starting with `'UnityPlayer' is abstract; cannot be instantiated`.

It seems from the Flutter side of things that they're [seeing the same](https://github.com/juicycleff/flutter-unity-view-widget/issues/839) and have a provisional [fix](https://github.com/ritolika/flutter-unity-view-widget/tree/Unity-2023.1), but it breaks compatibility between Unity versions.

**Comment by anothercog** [comment]
I know this is an old issue, but it was stumping me for a while. I've found a solution.

The problem with many 3rd party libraries that require access to Unity is that they're grabbing the **UnityPlayer** from the **mUnityPlayer** variable in the **MainActivity**, which is fine if you're not using Unity as a library, but otherwise, if you're able to put your own **mUnityPlayer** variable in **MainActivity** populated with the **UnityPlayer** instance, these libraries will work fine.

My solution was to add the following to the bottom of the **UPlayer** constructor in **\react-native-unity\android\src\main\java\com\azesmwayreactnativeunity\UPlayer.java**
```
        try {
            activity.getClass().getMethod("setUnityPlayer", java.lang.Object.class).invoke(activity, unityPlayer);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

Then your **MainActivity.java** class you need:
```
  public java.lang.Object mUnityPlayer = null;
  public void setUnityPlayer(java.lang.Object newUnityPlayer) {
    mUnityPlayer = newUnityPlayer;
  } 
```
The **MainActivity.java** being located in **\android\app\src\main\java\com\myprojectname\MainActivity.java**

Here's my full **MainActivity.java**:
```
package com.myprojectname;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;

public class MainActivity extends ReactActivity {

  public java.lang.Object mUnityPlayer = null;
  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "myprojectname";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. Here we use a util class {@link
   * DefaultReactActivityDelegate} which allows you to easily enable Fabric and Concurrent React
   * (aka React 18) with two boolean flags.
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new DefaultReactActivityDelegate(
        this,
        getMainComponentName(),
        // If you opted-in for the New Architecture, we enable the Fabric Renderer.
        DefaultNewArchitectureEntryPoint.getFabricEnabled());
  }

  public void setUnityPlayer(java.lang.Object newUnityPlayer) {
    mUnityPlayer = newUnityPlayer;
  } 
}
```

And the full **UPlayer.java** constructor
```
    public UPlayer(final Activity activity, final ReactNativeUnity.UnityPlayerCallback callback) throws ClassNotFoundException, InvocationTargetException, IllegalAccessException, InstantiationException {
        super();
        Class<?> _player = null;

        try {
            _player = Class.forName("com.unity3d.player.UnityPlayerForActivityOrService");
        } catch (ClassNotFoundException e) {
            _player = Class.forName("com.unity3d.player.UnityPlayer");
        }

        Constructor<?> constructor = _player.getConstructors()[1];
        unityPlayer = (UnityPlayer) constructor.newInstance(activity, new IUnityPlayerLifecycleEvents() {
            @Override
            public void onUnityPlayerUnloaded() {
                callback.onUnload();
            }

            @Override
            public void onUnityPlayerQuitted() {
                callback.onQuit();
            }
        });

        try {
            activity.getClass().getMethod("setUnityPlayer", java.lang.Object.class).invoke(activity, unityPlayer);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
