### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by GangaBS99** [azesmway/react-native-unity#73]
hi @azesmway , while running the react-native it showing as build failed. can you say what is the issue

![image](https://user-images.githubusercontent.com/96790034/236640374-c44f36a6-74f5-47ea-840f-296da9173321.png)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':azesmway_react-native-unity:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':azesmway_react-native-unity:debugCompileClasspath'.
   > Could not resolve project :unityLibrary.
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\react\Project\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)     
    at async Command.handleAction (D:\react\Project\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

**Comment by Luluno01** [comment]
According to my personal experience, the cause is either you forgot to define, or have not yet defined, the project `:unityLibrary` ([step 2](https://github.com/azesmway/react-native-unity/blob/main/README.md#android)), or the Unity Android project folder (`<path-to-exported-unity-android-project>/unityLibrary`) does not exist in your build environment (e.g., the exported Unity Android project folder is ignored unintentionally).

**Comment by GangaBS99** [comment]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\react\MyApp\unity\builds\android\unityLibrary\build.gradle' line: 50

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> java.io.FileNotFoundException: D:\react\MyApp\android\local.properties (The system cannot find the file specified)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

got this error after resolving that

**Comment by SaadSFS** [comment]
> According to my personal experience, the cause is either you forgot to define, or have not yet defined, the project `:unityLibrary` ([step 2](https://github.com/azesmway/react-native-unity/blob/main/README.md#android)), or the Unity Android project folder (`<path-to-exported-unity-android-project>/unityLibrary`) does not exist in your build environment (e.g., the exported Unity Android project folder is ignored unintentionally).

I have done with path, but still i got error and build failled

**Comment by Luluno01** [comment]
> > According to my personal experience, the cause is either you forgot to define, or have not yet defined, the project `:unityLibrary` ([step 2](https://github.com/azesmway/react-native-unity/blob/main/README.md#android)), or the Unity Android project folder (`<path-to-exported-unity-android-project>/unityLibrary`) does not exist in your build environment (e.g., the exported Unity Android project folder is ignored unintentionally).
> 
> I have done with path, but still i got error and build failled

Which error? According to your comments in #51, the error you have is different from this "Could not resolve project :unityLibrary" error.

**Comment by iamalinski** [comment]
Same error here. Any fix on this?
